apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: laravelsamp2
  name: laravelsamp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravelsamp2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laravelsamp2
    spec:
      containers:
      - image: laravelsamp2acr.azurecr.io/laravelsamp2:5a27b8da76a493467b71d7e69877fdc092517118
        name: laravelsamp2
        ports:
        - containerPort: 3000
        resources: {}
